
#define NS_PRIVATE_IMPLEMENTATION
#define CA_PRIVATE_IMPLEMENTATION
#define MTL_PRIVATE_IMPLEMENTATION
#include "Metal.hpp"

using namespace MTL;

struct macos_renderer_t
{
    Device* device;
    CommandQueue* command_queue;
    CA::MetalLayer* metal_layer;
    MTL::Buffer* vertex_buffer;
};

global_variable macos_renderer_t g_renderer;


struct Vertex
{
    float pos[2];
    float color[3];
};

static Vertex g_triangle[3] =
{
    { {  0.0f,  0.5f }, { 1, 0, 0 } },
    { { -0.5f, -0.5f }, { 0, 1, 0 } },
    { {  0.5f, -0.5f }, { 0, 0, 1 } },
};



internal_f void
Metal_Init(macos_renderer_t *renderer)
{
    renderer->device = 0;
    renderer->device = MTLCreateSystemDefaultDevice();
    
    assert(renderer->device);
    
    renderer->command_queue = renderer->device->newCommandQueue();
    renderer->metal_layer = CA::MetalLayer::layer();
    
    renderer->metal_layer->setDevice(renderer->device);
    renderer->metal_layer->setPixelFormat(PixelFormatBGRA8Unorm);
    renderer->metal_layer->setFramebufferOnly(true);
    
    renderer->vertex_buffer = renderer->device->newBuffer(&g_triangle, sizeof(g_triangle), ResourceStorageModeShared);
    
    
    // Compile shaders
    NS::Error* error = nil;
    
    NS::String* source = NS::String::string(R"(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #include <metal_stdlib>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            using namespace metal;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            struct VertexIn {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                float2 pos [[attribute(0)]];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                float3 color [[attribute(1)]];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            struct VertexOut {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                float4 position [[position]];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                float3 color;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            vertex VertexOut vs_main(VertexIn in [[stage_in]])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                VertexOut out;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                out.position = float4(in.pos, 0.0, 1.0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                out.color = in.color;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return out;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fragment float4 fs_main(VertexOut in [[stage_in]])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return float4(in.color, 1.0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )", NS::UTF8StringEncoding);
    
    MTL::Library* library = renderer->device->newLibrary(source, 0, &error);
    
    MTL::RenderPipelineDescriptor* desc = MTL::RenderPipelineDescriptor::alloc();
    desc->init();
    
    NS::String* v_function_name = NS::String::string("vs_main", NS::UTF8StringEncoding);
    NS::String* f_function_name = NS::String::string("fs_main", NS::UTF8StringEncoding);
    MTL::Function* vertex_shader = library->newFunction(v_function_name);
    MTL::Function* fragment_shader = library->newFunction(v_function_name);
    
    desc->setVertexFunction(vertex_shader);
    desc->setFragmentFunction(fragment_shader);
    
    
    RenderPipelineColorAttachmentDescriptor* color_desc = RenderPipelineColorAttachmentDescriptor::alloc();
    color_desc->setPixelFormat(MTL::PixelFormatBGRA8Unorm);
    desc->colorAttachments()->setObject(color_desc,0);
    
    color_desc->release();
    library->release();
    
    
    
}


global_f bool
RendererInit()
{
    
    Metal_Init(&g_renderer);
    
    
    return true;
}


global_f void
RendererUpdate(engine_shared_data_t *engine_data){}


global_f void
RendererComputeImportedMesh(engine_shared_data_t *engine_data, mesh_t* mesh, const char* texture_name)
{}




global_f void
RendererShutDown()
{
    g_renderer.device->release();
}


